"""
AppImage Manager - Sudo Helper
Provides utilities for running commands with elevated privileges.
"""

import subprocess
import logging
import tkinter as tk
from tkinter import simpledialog
import os
import sys
import tempfile

from i18n import _

logger = logging.getLogger(__name__)

class PasswordDialog(simpledialog.Dialog):
    """Custom dialog for securely requesting a password."""

    def __init__(self, parent, title, prompt):
        self.prompt = prompt
        super().__init__(parent, title)

    def body(self, master):
        """Create dialog body."""
        tk.Label(master, text=self.prompt, wraplength=300).grid(row=0, padx=5, pady=5, sticky="w")
        
        self.password_var = tk.StringVar()
        self.password_entry = tk.Entry(master, textvariable=self.password_var, show="*", width=30)
        self.password_entry.grid(row=1, padx=5, pady=5)
        self.password_entry.focus_set()
        
        return self.password_entry  # Initial focus

    def apply(self):
        """Store the password when OK is clicked."""
        self.result = self.password_var.get()

def get_sudo_password(parent, title=None, prompt=None):
    """Show a dialog to get sudo password from the user.
    
    Args:
        parent: Parent Tkinter window
        title (str, optional): Dialog title
        prompt (str, optional): Password prompt message
        
    Returns:
        str: The entered password or None if cancelled
    """
    if title is None:
        title = _("Authentication Required")
    
    if prompt is None:
        prompt = _("msg_enter_password")

    dialog = PasswordDialog(parent, title, prompt)
    return dialog.result  # Will be None if cancelled

def run_with_sudo(command, password, stdin_input=None):
    """Run a command with sudo privileges using the provided password.
    
    Args:
        command (list): Command and arguments to run
        password (str): Sudo password
        stdin_input (str, optional): Data to pass to command's stdin
        
    Returns:
        tuple: (returncode, stdout, stderr)
    """
    try:
        # Construct sudo command
        sudo_command = ["sudo", "-S"] + command

        # Run the command
        process = subprocess.Popen(
            sudo_command,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )

        # Send the password followed by any additional stdin input
        input_data = password + "\n"
        if stdin_input:
            input_data += stdin_input
        
        stdout, stderr = process.communicate(input=input_data)
        
        # Check if auth failed (common sudo error messages)
        if "incorrect password" in stderr.lower() or "sorry, try again" in stderr.lower():
            logger.error("Authentication failed: Incorrect password")
            return (1, stdout, stderr)
            
        return (process.returncode, stdout, stderr)
    except Exception as e:
        logger.error(f"Error running command with sudo: {e}")
        return (1, "", str(e))

def check_sudo_password(password):
    """Check if the provided sudo password is valid.
    
    Args:
        password (str): Sudo password to check
        
    Returns:
        bool: True if password is valid, False otherwise
    """
    try:
        # Use a simple, harmless command to check the password
        returncode, _, _ = run_with_sudo(["true"], password)
        return returncode == 0
    except Exception as e:
        logger.error(f"Error checking sudo password: {e}")
        return False

def create_root_helper_script(commands):
    """Create a temporary script that will be executed with sudo.
    
    This is useful for running multiple commands with a single sudo password prompt.
    
    Args:
        commands (list): List of shell commands to include in the script
        
    Returns:
        str: Path to the temporary script
    """
    try:
        # Create a temporary script file
        fd, script_path = tempfile.mkstemp(suffix='.sh')
        
        with os.fdopen(fd, 'w') as f:
            f.write("#!/bin/bash\n\n")
            f.write("# Generated by AppImage Manager\n\n")
            
            # Add commands
            for cmd in commands:
                f.write(f"{cmd}\n")
        
        # Make executable
        os.chmod(script_path, 0o755)
        
        return script_path
    except Exception as e:
        logger.error(f"Error creating helper script: {e}")
        return None 